apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sampleapp7
    version: "1"
  name: sampleapp7
  namespace: gr5
spec:
  containers:
  - image: nginx
    name: sampleapp7
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
